version: '3'
services:
  web:
    build:
      context: 'client/'
      dockerfile: 'Dockerfile'
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - 'data:/usr/share/nginx/html/db/'
      #- './client:/usr/share/nginx/html/'
  grpc:
    build:
      context: '.'
      dockerfile: './server/Dockerfile'
    ports:
      - '3000:3000/tcp'
    volumes:
      - 'data:/db/'
volumes:
  data:

