name: python-lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: python-lint
      uses: CyberZHG/github-action-python-lint@0.0.2
      with:
        args: "--max-line-length=120 probe/"
